# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.runtime_agent_run_async_status_response import RuntimeAgentRunAsyncStatusResponse

class TestRuntimeAgentRunAsyncStatusResponse(unittest.TestCase):
    """RuntimeAgentRunAsyncStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeAgentRunAsyncStatusResponse:
        """Test RuntimeAgentRunAsyncStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeAgentRunAsyncStatusResponse`
        """
        model = RuntimeAgentRunAsyncStatusResponse()
        if include_optional:
            return RuntimeAgentRunAsyncStatusResponse(
                cancel_requested = True,
                decomposition_sub_questions = [
                    ''
                    ],
                elapsed_ms = 56,
                error = '',
                finished_at = 1.337,
                job_id = '',
                message = '',
                output = '',
                result = openapi_client.models.runtime_agent_run_response.RuntimeAgentRunResponse(
                    final_citations = [
                        openapi_client.models.citation_source_row.CitationSourceRow(
                            citation_index = 1.0, 
                            content = '', 
                            document_id = '', 
                            rank = 1.0, 
                            score = 1.337, 
                            source = '', 
                            title = '', )
                        ], 
                    main_question = '', 
                    output = '', 
                    sub_qa = [
                        openapi_client.models.sub_question_answer.SubQuestionAnswer(
                            answerable = True, 
                            expanded_query = '', 
                            sub_agent_response = '', 
                            sub_answer = '', 
                            sub_question = '', 
                            tool_call_input = '', 
                            verification_reason = '', )
                        ], ),
                run_id = '',
                stage = '',
                stages = [
                    openapi_client.models.agent_run_stage_metadata.AgentRunStageMetadata(
                        emitted_at = 1.337, 
                        lane_index = 56, 
                        lane_total = 56, 
                        stage = '', 
                        status = '', 
                        sub_question = '', )
                    ],
                started_at = 1.337,
                status = '',
                sub_qa = [
                    openapi_client.models.sub_question_answer.SubQuestionAnswer(
                        answerable = True, 
                        expanded_query = '', 
                        sub_agent_response = '', 
                        sub_answer = '', 
                        sub_question = '', 
                        tool_call_input = '', 
                        verification_reason = '', )
                    ],
                sub_question_artifacts = [
                    openapi_client.models.sub_question_artifacts.SubQuestionArtifacts(
                        citation_rows_by_index = {
                            'key' : openapi_client.models.citation_source_row.CitationSourceRow(
                                citation_index = 1.0, 
                                content = '', 
                                document_id = '', 
                                rank = 1.0, 
                                score = 1.337, 
                                source = '', 
                                title = '', )
                            }, 
                        expanded_queries = [
                            ''
                            ], 
                        reranked_docs = [
                            openapi_client.models.citation_source_row.CitationSourceRow(
                                citation_index = 1.0, 
                                content = '', 
                                document_id = '', 
                                rank = 1.0, 
                                score = 1.337, 
                                source = '', 
                                title = '', )
                            ], 
                        retrieval_provenance = [
                            None
                            ], 
                        retrieved_docs = [
                            
                            ], 
                        sub_answer = '', 
                        sub_question = '', )
                    ]
            )
        else:
            return RuntimeAgentRunAsyncStatusResponse(
                job_id = '',
                status = '',
        )
        """

    def testRuntimeAgentRunAsyncStatusResponse(self):
        """Test RuntimeAgentRunAsyncStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
