# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.runtime_agent_run_request import RuntimeAgentRunRequest

class TestRuntimeAgentRunRequest(unittest.TestCase):
    """RuntimeAgentRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeAgentRunRequest:
        """Test RuntimeAgentRunRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeAgentRunRequest`
        """
        model = RuntimeAgentRunRequest()
        if include_optional:
            return RuntimeAgentRunRequest(
                controls = openapi_client.models.runtime_agent_run_controls.RuntimeAgentRunControls(
                    hitl = null, 
                    query_expansion = null, 
                    rerank = null, ),
                custom_prompts = openapi_client.models.runtime_custom_prompts.RuntimeCustomPrompts(
                    subanswer = '', 
                    synthesis = '', ),
                query = '0',
                runtime_config = openapi_client.models.runtime_agent_run_runtime_config.RuntimeAgentRunRuntimeConfig(
                    query_expansion = null, 
                    rerank = null, ),
                thread_id = ''
            )
        else:
            return RuntimeAgentRunRequest(
                query = '0',
        )
        """

    def testRuntimeAgentRunRequest(self):
        """Test RuntimeAgentRunRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
