# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.internal_data_api import InternalDataApi


class TestInternalDataApi(unittest.TestCase):
    """InternalDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InternalDataApi()

    def tearDown(self) -> None:
        pass

    def test_list_wiki_sources_api_internal_data_wiki_sources_get(self) -> None:
        """Test case for list_wiki_sources_api_internal_data_wiki_sources_get

        List Wiki Sources
        """
        pass

    def test_load_data_api_internal_data_load_post(self) -> None:
        """Test case for load_data_api_internal_data_load_post

        Load Data
        """
        pass

    def test_wipe_data_api_internal_data_wipe_post(self) -> None:
        """Test case for wipe_data_api_internal_data_wipe_post

        Wipe Data
        """
        pass


if __name__ == '__main__':
    unittest.main()
