# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_runtime_agent_run_api_agents_run_post(self) -> None:
        """Test case for runtime_agent_run_api_agents_run_post

        Runtime Agent Run
        """
        pass

    def test_runtime_agent_run_async_api_agents_run_async_post(self) -> None:
        """Test case for runtime_agent_run_async_api_agents_run_async_post

        Runtime Agent Run Async
        """
        pass

    def test_runtime_agent_run_cancel_api_agents_run_cancel_job_id_post(self) -> None:
        """Test case for runtime_agent_run_cancel_api_agents_run_cancel_job_id_post

        Runtime Agent Run Cancel
        """
        pass

    def test_runtime_agent_run_events_api_agents_run_events_job_id_get(self) -> None:
        """Test case for runtime_agent_run_events_api_agents_run_events_job_id_get

        Runtime Agent Run Events
        """
        pass

    def test_runtime_agent_run_resume_api_agents_run_resume_job_id_post(self) -> None:
        """Test case for runtime_agent_run_resume_api_agents_run_resume_job_id_post

        Runtime Agent Run Resume
        """
        pass

    def test_runtime_agent_run_status_api_agents_run_status_job_id_get(self) -> None:
        """Test case for runtime_agent_run_status_api_agents_run_status_job_id_get

        Runtime Agent Run Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
