# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wiki_load_input import WikiLoadInput

class TestWikiLoadInput(unittest.TestCase):
    """WikiLoadInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WikiLoadInput:
        """Test WikiLoadInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WikiLoadInput`
        """
        model = WikiLoadInput()
        if include_optional:
            return WikiLoadInput(
                source_id = '0'
            )
        else:
            return WikiLoadInput(
                source_id = '0',
        )
        """

    def testWikiLoadInput(self):
        """Test WikiLoadInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
