# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sub_question_artifacts import SubQuestionArtifacts

class TestSubQuestionArtifacts(unittest.TestCase):
    """SubQuestionArtifacts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubQuestionArtifacts:
        """Test SubQuestionArtifacts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubQuestionArtifacts`
        """
        model = SubQuestionArtifacts()
        if include_optional:
            return SubQuestionArtifacts(
                citation_rows_by_index = {
                    'key' : openapi_client.models.citation_source_row.CitationSourceRow(
                        citation_index = 1.0, 
                        content = '', 
                        document_id = '', 
                        rank = 1.0, 
                        score = 1.337, 
                        source = '', 
                        title = '', )
                    },
                expanded_queries = [
                    ''
                    ],
                reranked_docs = [
                    openapi_client.models.citation_source_row.CitationSourceRow(
                        citation_index = 1.0, 
                        content = '', 
                        document_id = '', 
                        rank = 1.0, 
                        score = 1.337, 
                        source = '', 
                        title = '', )
                    ],
                retrieval_provenance = [
                    None
                    ],
                retrieved_docs = [
                    openapi_client.models.citation_source_row.CitationSourceRow(
                        citation_index = 1.0, 
                        content = '', 
                        document_id = '', 
                        rank = 1.0, 
                        score = 1.337, 
                        source = '', 
                        title = '', )
                    ],
                sub_answer = '',
                sub_question = ''
            )
        else:
            return SubQuestionArtifacts(
                sub_question = '',
        )
        """

    def testSubQuestionArtifacts(self):
        """Test SubQuestionArtifacts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
