# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.runtime_agent_run_runtime_config import RuntimeAgentRunRuntimeConfig

class TestRuntimeAgentRunRuntimeConfig(unittest.TestCase):
    """RuntimeAgentRunRuntimeConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeAgentRunRuntimeConfig:
        """Test RuntimeAgentRunRuntimeConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeAgentRunRuntimeConfig`
        """
        model = RuntimeAgentRunRuntimeConfig()
        if include_optional:
            return RuntimeAgentRunRuntimeConfig(
                query_expansion = openapi_client.models.runtime_query_expansion_control.RuntimeQueryExpansionControl(
                    enabled = True, ),
                rerank = openapi_client.models.runtime_rerank_control.RuntimeRerankControl(
                    enabled = True, )
            )
        else:
            return RuntimeAgentRunRuntimeConfig(
        )
        """

    def testRuntimeAgentRunRuntimeConfig(self):
        """Test RuntimeAgentRunRuntimeConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
