# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.resume import Resume

class TestResume(unittest.TestCase):
    """Resume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Resume:
        """Test Resume
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Resume`
        """
        model = Resume()
        if include_optional:
            return Resume(
                checkpoint_id = '0',
                decisions = [
                    openapi_client.models.runtime_query_expansion_decision.RuntimeQueryExpansionDecision(
                        action = 'approve', 
                        edited_query = '', 
                        expansion_id = '0', )
                    ]
            )
        else:
            return Resume(
                checkpoint_id = '0',
                decisions = [
                    openapi_client.models.runtime_query_expansion_decision.RuntimeQueryExpansionDecision(
                        action = 'approve', 
                        edited_query = '', 
                        expansion_id = '0', )
                    ],
        )
        """

    def testResume(self):
        """Test Resume"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
