# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.runtime_subquestion_resume_envelope import RuntimeSubquestionResumeEnvelope

class TestRuntimeSubquestionResumeEnvelope(unittest.TestCase):
    """RuntimeSubquestionResumeEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeSubquestionResumeEnvelope:
        """Test RuntimeSubquestionResumeEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeSubquestionResumeEnvelope`
        """
        model = RuntimeSubquestionResumeEnvelope()
        if include_optional:
            return RuntimeSubquestionResumeEnvelope(
                checkpoint_id = '0',
                decisions = [
                    openapi_client.models.runtime_subquestion_decision.RuntimeSubquestionDecision(
                        action = 'approve', 
                        edited_text = '', 
                        subquestion_id = '0', )
                    ]
            )
        else:
            return RuntimeSubquestionResumeEnvelope(
                checkpoint_id = '0',
                decisions = [
                    openapi_client.models.runtime_subquestion_decision.RuntimeSubquestionDecision(
                        action = 'approve', 
                        edited_text = '', 
                        subquestion_id = '0', )
                    ],
        )
        """

    def testRuntimeSubquestionResumeEnvelope(self):
        """Test RuntimeSubquestionResumeEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
