# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.internal_data_load_job_status_response import InternalDataLoadJobStatusResponse

class TestInternalDataLoadJobStatusResponse(unittest.TestCase):
    """InternalDataLoadJobStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalDataLoadJobStatusResponse:
        """Test InternalDataLoadJobStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalDataLoadJobStatusResponse`
        """
        model = InternalDataLoadJobStatusResponse()
        if include_optional:
            return InternalDataLoadJobStatusResponse(
                completed = 56,
                error = '',
                job_id = '',
                message = '',
                response = openapi_client.models.internal_data_load_response.InternalDataLoadResponse(
                    chunks_created = 56, 
                    documents_loaded = 56, 
                    source_type = '', 
                    status = 'success', ),
                status = '',
                total = 56
            )
        else:
            return InternalDataLoadJobStatusResponse(
                completed = 56,
                job_id = '',
                message = '',
                status = '',
                total = 56,
        )
        """

    def testInternalDataLoadJobStatusResponse(self):
        """Test InternalDataLoadJobStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
