# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.internal_document_input import InternalDocumentInput

class TestInternalDocumentInput(unittest.TestCase):
    """InternalDocumentInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalDocumentInput:
        """Test InternalDocumentInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalDocumentInput`
        """
        model = InternalDocumentInput()
        if include_optional:
            return InternalDocumentInput(
                content = '0',
                source_ref = '',
                source_url = '',
                title = '0'
            )
        else:
            return InternalDocumentInput(
                content = '0',
                title = '0',
        )
        """

    def testInternalDocumentInput(self):
        """Test InternalDocumentInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
