# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.citation_source_row import CitationSourceRow

class TestCitationSourceRow(unittest.TestCase):
    """CitationSourceRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CitationSourceRow:
        """Test CitationSourceRow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CitationSourceRow`
        """
        model = CitationSourceRow()
        if include_optional:
            return CitationSourceRow(
                citation_index = 1.0,
                content = '',
                document_id = '',
                rank = 1.0,
                score = 1.337,
                source = '',
                title = ''
            )
        else:
            return CitationSourceRow(
                citation_index = 1.0,
                rank = 1.0,
        )
        """

    def testCitationSourceRow(self):
        """Test CitationSourceRow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
