# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sub_question_answer import SubQuestionAnswer

class TestSubQuestionAnswer(unittest.TestCase):
    """SubQuestionAnswer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubQuestionAnswer:
        """Test SubQuestionAnswer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubQuestionAnswer`
        """
        model = SubQuestionAnswer()
        if include_optional:
            return SubQuestionAnswer(
                answerable = True,
                expanded_query = '',
                sub_agent_response = '',
                sub_answer = '',
                sub_question = '',
                tool_call_input = '',
                verification_reason = ''
            )
        else:
            return SubQuestionAnswer(
                sub_answer = '',
                sub_question = '',
        )
        """

    def testSubQuestionAnswer(self):
        """Test SubQuestionAnswer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
