# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.agent_run_stage_metadata import AgentRunStageMetadata

class TestAgentRunStageMetadata(unittest.TestCase):
    """AgentRunStageMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentRunStageMetadata:
        """Test AgentRunStageMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentRunStageMetadata`
        """
        model = AgentRunStageMetadata()
        if include_optional:
            return AgentRunStageMetadata(
                emitted_at = 1.337,
                lane_index = 56,
                lane_total = 56,
                stage = '',
                status = '',
                sub_question = ''
            )
        else:
            return AgentRunStageMetadata(
                stage = '',
                status = '',
        )
        """

    def testAgentRunStageMetadata(self):
        """Test AgentRunStageMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
