# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.runtime_agent_run_response import RuntimeAgentRunResponse

class TestRuntimeAgentRunResponse(unittest.TestCase):
    """RuntimeAgentRunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeAgentRunResponse:
        """Test RuntimeAgentRunResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeAgentRunResponse`
        """
        model = RuntimeAgentRunResponse()
        if include_optional:
            return RuntimeAgentRunResponse(
                final_citations = [
                    openapi_client.models.citation_source_row.CitationSourceRow(
                        citation_index = 1.0, 
                        content = '', 
                        document_id = '', 
                        rank = 1.0, 
                        score = 1.337, 
                        source = '', 
                        title = '', )
                    ],
                main_question = '',
                output = '',
                sub_qa = [
                    openapi_client.models.sub_question_answer.SubQuestionAnswer(
                        answerable = True, 
                        expanded_query = '', 
                        sub_agent_response = '', 
                        sub_answer = '', 
                        sub_question = '', 
                        tool_call_input = '', 
                        verification_reason = '', )
                    ],
                thread_id = ''
            )
        else:
            return RuntimeAgentRunResponse(
                output = '',
        )
        """

    def testRuntimeAgentRunResponse(self):
        """Test RuntimeAgentRunResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
