# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.runtime_subquestion_hitl_control import RuntimeSubquestionHitlControl

class TestRuntimeSubquestionHitlControl(unittest.TestCase):
    """RuntimeSubquestionHitlControl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeSubquestionHitlControl:
        """Test RuntimeSubquestionHitlControl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeSubquestionHitlControl`
        """
        model = RuntimeSubquestionHitlControl()
        if include_optional:
            return RuntimeSubquestionHitlControl(
                enabled = True
            )
        else:
            return RuntimeSubquestionHitlControl(
        )
        """

    def testRuntimeSubquestionHitlControl(self):
        """Test RuntimeSubquestionHitlControl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
