# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.runtime_subquestion_decision import RuntimeSubquestionDecision

class TestRuntimeSubquestionDecision(unittest.TestCase):
    """RuntimeSubquestionDecision unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeSubquestionDecision:
        """Test RuntimeSubquestionDecision
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeSubquestionDecision`
        """
        model = RuntimeSubquestionDecision()
        if include_optional:
            return RuntimeSubquestionDecision(
                action = 'approve',
                edited_text = '',
                subquestion_id = '0'
            )
        else:
            return RuntimeSubquestionDecision(
                action = 'approve',
                subquestion_id = '0',
        )
        """

    def testRuntimeSubquestionDecision(self):
        """Test RuntimeSubquestionDecision"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
