# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AgentRunStageMetadata(BaseModel):
    """
    AgentRunStageMetadata
    """ # noqa: E501
    emitted_at: Optional[Union[StrictFloat, StrictInt]] = None
    lane_index: Optional[StrictInt] = 0
    lane_total: Optional[StrictInt] = 0
    stage: StrictStr
    status: StrictStr
    sub_question: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["emitted_at", "lane_index", "lane_total", "stage", "status", "sub_question"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentRunStageMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if emitted_at (nullable) is None
        # and model_fields_set contains the field
        if self.emitted_at is None and "emitted_at" in self.model_fields_set:
            _dict['emitted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentRunStageMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "emitted_at": obj.get("emitted_at"),
            "lane_index": obj.get("lane_index") if obj.get("lane_index") is not None else 0,
            "lane_total": obj.get("lane_total") if obj.get("lane_total") is not None else 0,
            "stage": obj.get("stage"),
            "status": obj.get("status"),
            "sub_question": obj.get("sub_question") if obj.get("sub_question") is not None else ''
        })
        return _obj


