# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CitationSourceRow(BaseModel):
    """
    CitationSourceRow
    """ # noqa: E501
    citation_index: Annotated[int, Field(strict=True, ge=1)]
    content: Optional[StrictStr] = ''
    document_id: Optional[StrictStr] = ''
    rank: Annotated[int, Field(strict=True, ge=1)]
    score: Optional[Union[StrictFloat, StrictInt]] = None
    source: Optional[StrictStr] = ''
    title: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["citation_index", "content", "document_id", "rank", "score", "source", "title"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CitationSourceRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CitationSourceRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "citation_index": obj.get("citation_index"),
            "content": obj.get("content") if obj.get("content") is not None else '',
            "document_id": obj.get("document_id") if obj.get("document_id") is not None else '',
            "rank": obj.get("rank"),
            "score": obj.get("score"),
            "source": obj.get("source") if obj.get("source") is not None else '',
            "title": obj.get("title") if obj.get("title") is not None else ''
        })
        return _obj


