# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.internal_document_input import InternalDocumentInput
from openapi_client.models.wiki_load_input import WikiLoadInput
from typing import Optional, Set
from typing_extensions import Self

class InternalDataLoadRequest(BaseModel):
    """
    InternalDataLoadRequest
    """ # noqa: E501
    documents: Optional[List[InternalDocumentInput]] = None
    source_type: Optional[StrictStr] = 'inline'
    wiki: Optional[WikiLoadInput] = None
    __properties: ClassVar[List[str]] = ["documents", "source_type", "wiki"]

    @field_validator('source_type')
    def source_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['inline', 'wiki']):
            raise ValueError("must be one of enum values ('inline', 'wiki')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalDataLoadRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in documents (list)
        _items = []
        if self.documents:
            for _item_documents in self.documents:
                if _item_documents:
                    _items.append(_item_documents.to_dict())
            _dict['documents'] = _items
        # override the default output from pydantic by calling `to_dict()` of wiki
        if self.wiki:
            _dict['wiki'] = self.wiki.to_dict()
        # set to None if documents (nullable) is None
        # and model_fields_set contains the field
        if self.documents is None and "documents" in self.model_fields_set:
            _dict['documents'] = None

        # set to None if wiki (nullable) is None
        # and model_fields_set contains the field
        if self.wiki is None and "wiki" in self.model_fields_set:
            _dict['wiki'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalDataLoadRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "documents": [InternalDocumentInput.from_dict(_item) for _item in obj["documents"]] if obj.get("documents") is not None else None,
            "source_type": obj.get("source_type") if obj.get("source_type") is not None else 'inline',
            "wiki": WikiLoadInput.from_dict(obj["wiki"]) if obj.get("wiki") is not None else None
        })
        return _obj


