# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.runtime_query_expansion_hitl_control import RuntimeQueryExpansionHitlControl
from openapi_client.models.runtime_subquestion_hitl_control import RuntimeSubquestionHitlControl
from typing import Optional, Set
from typing_extensions import Self

class RuntimeHitlControl(BaseModel):
    """
    RuntimeHitlControl
    """ # noqa: E501
    enabled: Optional[StrictBool] = False
    query_expansion: Optional[RuntimeQueryExpansionHitlControl] = None
    subquestions: Optional[RuntimeSubquestionHitlControl] = None
    __properties: ClassVar[List[str]] = ["enabled", "query_expansion", "subquestions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuntimeHitlControl from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of query_expansion
        if self.query_expansion:
            _dict['query_expansion'] = self.query_expansion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subquestions
        if self.subquestions:
            _dict['subquestions'] = self.subquestions.to_dict()
        # set to None if query_expansion (nullable) is None
        # and model_fields_set contains the field
        if self.query_expansion is None and "query_expansion" in self.model_fields_set:
            _dict['query_expansion'] = None

        # set to None if subquestions (nullable) is None
        # and model_fields_set contains the field
        if self.subquestions is None and "subquestions" in self.model_fields_set:
            _dict['subquestions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuntimeHitlControl from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else False,
            "query_expansion": RuntimeQueryExpansionHitlControl.from_dict(obj["query_expansion"]) if obj.get("query_expansion") is not None else None,
            "subquestions": RuntimeSubquestionHitlControl.from_dict(obj["subquestions"]) if obj.get("subquestions") is not None else None
        })
        return _obj


