# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.citation_source_row import CitationSourceRow
from openapi_client.models.sub_question_answer import SubQuestionAnswer
from typing import Optional, Set
from typing_extensions import Self

class RuntimeAgentRunResponse(BaseModel):
    """
    RuntimeAgentRunResponse
    """ # noqa: E501
    final_citations: Optional[List[CitationSourceRow]] = None
    main_question: Optional[StrictStr] = ''
    output: StrictStr
    sub_answers: Optional[List[SubQuestionAnswer]] = None
    sub_qa: Optional[List[SubQuestionAnswer]] = None
    thread_id: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["final_citations", "main_question", "output", "sub_answers", "sub_qa", "thread_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuntimeAgentRunResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in final_citations (list)
        _items = []
        if self.final_citations:
            for _item_final_citations in self.final_citations:
                if _item_final_citations:
                    _items.append(_item_final_citations.to_dict())
            _dict['final_citations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_answers (list)
        _items = []
        if self.sub_answers:
            for _item_sub_answers in self.sub_answers:
                if _item_sub_answers:
                    _items.append(_item_sub_answers.to_dict())
            _dict['sub_answers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_qa (list)
        _items = []
        if self.sub_qa:
            for _item_sub_qa in self.sub_qa:
                if _item_sub_qa:
                    _items.append(_item_sub_qa.to_dict())
            _dict['sub_qa'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuntimeAgentRunResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "final_citations": [CitationSourceRow.from_dict(_item) for _item in obj["final_citations"]] if obj.get("final_citations") is not None else None,
            "main_question": obj.get("main_question") if obj.get("main_question") is not None else '',
            "output": obj.get("output"),
            "sub_answers": [SubQuestionAnswer.from_dict(_item) for _item in obj["sub_answers"]] if obj.get("sub_answers") is not None else None,
            "sub_qa": [SubQuestionAnswer.from_dict(_item) for _item in obj["sub_qa"]] if obj.get("sub_qa") is not None else None,
            "thread_id": obj.get("thread_id") if obj.get("thread_id") is not None else ''
        })
        return _obj


