# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.runtime_agent_run_controls import RuntimeAgentRunControls
from openapi_client.models.runtime_agent_run_runtime_config import RuntimeAgentRunRuntimeConfig
from openapi_client.models.runtime_custom_prompts import RuntimeCustomPrompts
from typing import Optional, Set
from typing_extensions import Self

class RuntimeAgentRunRequest(BaseModel):
    """
    RuntimeAgentRunRequest
    """ # noqa: E501
    controls: Optional[RuntimeAgentRunControls] = None
    custom_prompts: Optional[RuntimeCustomPrompts] = None
    query: Annotated[str, Field(min_length=1, strict=True)]
    runtime_config: Optional[RuntimeAgentRunRuntimeConfig] = None
    thread_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["controls", "custom_prompts", "query", "runtime_config", "thread_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuntimeAgentRunRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of controls
        if self.controls:
            _dict['controls'] = self.controls.to_dict()
        # override the default output from pydantic by calling `to_dict()` of custom_prompts
        if self.custom_prompts:
            _dict['custom_prompts'] = self.custom_prompts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of runtime_config
        if self.runtime_config:
            _dict['runtime_config'] = self.runtime_config.to_dict()
        # set to None if controls (nullable) is None
        # and model_fields_set contains the field
        if self.controls is None and "controls" in self.model_fields_set:
            _dict['controls'] = None

        # set to None if custom_prompts (nullable) is None
        # and model_fields_set contains the field
        if self.custom_prompts is None and "custom_prompts" in self.model_fields_set:
            _dict['custom_prompts'] = None

        # set to None if runtime_config (nullable) is None
        # and model_fields_set contains the field
        if self.runtime_config is None and "runtime_config" in self.model_fields_set:
            _dict['runtime_config'] = None

        # set to None if thread_id (nullable) is None
        # and model_fields_set contains the field
        if self.thread_id is None and "thread_id" in self.model_fields_set:
            _dict['thread_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuntimeAgentRunRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "controls": RuntimeAgentRunControls.from_dict(obj["controls"]) if obj.get("controls") is not None else None,
            "custom_prompts": RuntimeCustomPrompts.from_dict(obj["custom_prompts"]) if obj.get("custom_prompts") is not None else None,
            "query": obj.get("query"),
            "runtime_config": RuntimeAgentRunRuntimeConfig.from_dict(obj["runtime_config"]) if obj.get("runtime_config") is not None else None,
            "thread_id": obj.get("thread_id")
        })
        return _obj


