# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.agent_run_stage_metadata import AgentRunStageMetadata
from openapi_client.models.runtime_agent_run_response import RuntimeAgentRunResponse
from openapi_client.models.sub_question_answer import SubQuestionAnswer
from openapi_client.models.sub_question_artifacts import SubQuestionArtifacts
from typing import Optional, Set
from typing_extensions import Self

class RuntimeAgentRunAsyncStatusResponse(BaseModel):
    """
    RuntimeAgentRunAsyncStatusResponse
    """ # noqa: E501
    cancel_requested: Optional[StrictBool] = False
    decomposition_sub_questions: Optional[List[StrictStr]] = None
    elapsed_ms: Optional[StrictInt] = None
    error: Optional[StrictStr] = None
    finished_at: Optional[Union[StrictFloat, StrictInt]] = None
    job_id: StrictStr
    message: Optional[StrictStr] = ''
    output: Optional[StrictStr] = ''
    result: Optional[RuntimeAgentRunResponse] = None
    run_id: Optional[StrictStr] = ''
    stage: Optional[StrictStr] = ''
    stages: Optional[List[AgentRunStageMetadata]] = None
    started_at: Optional[Union[StrictFloat, StrictInt]] = None
    status: StrictStr
    sub_qa: Optional[List[SubQuestionAnswer]] = None
    sub_question_artifacts: Optional[List[SubQuestionArtifacts]] = None
    thread_id: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["cancel_requested", "decomposition_sub_questions", "elapsed_ms", "error", "finished_at", "job_id", "message", "output", "result", "run_id", "stage", "stages", "started_at", "status", "sub_qa", "sub_question_artifacts", "thread_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuntimeAgentRunAsyncStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of result
        if self.result:
            _dict['result'] = self.result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in stages (list)
        _items = []
        if self.stages:
            for _item_stages in self.stages:
                if _item_stages:
                    _items.append(_item_stages.to_dict())
            _dict['stages'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_qa (list)
        _items = []
        if self.sub_qa:
            for _item_sub_qa in self.sub_qa:
                if _item_sub_qa:
                    _items.append(_item_sub_qa.to_dict())
            _dict['sub_qa'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_question_artifacts (list)
        _items = []
        if self.sub_question_artifacts:
            for _item_sub_question_artifacts in self.sub_question_artifacts:
                if _item_sub_question_artifacts:
                    _items.append(_item_sub_question_artifacts.to_dict())
            _dict['sub_question_artifacts'] = _items
        # set to None if elapsed_ms (nullable) is None
        # and model_fields_set contains the field
        if self.elapsed_ms is None and "elapsed_ms" in self.model_fields_set:
            _dict['elapsed_ms'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict['finished_at'] = None

        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuntimeAgentRunAsyncStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cancel_requested": obj.get("cancel_requested") if obj.get("cancel_requested") is not None else False,
            "decomposition_sub_questions": obj.get("decomposition_sub_questions"),
            "elapsed_ms": obj.get("elapsed_ms"),
            "error": obj.get("error"),
            "finished_at": obj.get("finished_at"),
            "job_id": obj.get("job_id"),
            "message": obj.get("message") if obj.get("message") is not None else '',
            "output": obj.get("output") if obj.get("output") is not None else '',
            "result": RuntimeAgentRunResponse.from_dict(obj["result"]) if obj.get("result") is not None else None,
            "run_id": obj.get("run_id") if obj.get("run_id") is not None else '',
            "stage": obj.get("stage") if obj.get("stage") is not None else '',
            "stages": [AgentRunStageMetadata.from_dict(_item) for _item in obj["stages"]] if obj.get("stages") is not None else None,
            "started_at": obj.get("started_at"),
            "status": obj.get("status"),
            "sub_qa": [SubQuestionAnswer.from_dict(_item) for _item in obj["sub_qa"]] if obj.get("sub_qa") is not None else None,
            "sub_question_artifacts": [SubQuestionArtifacts.from_dict(_item) for _item in obj["sub_question_artifacts"]] if obj.get("sub_question_artifacts") is not None else None,
            "thread_id": obj.get("thread_id") if obj.get("thread_id") is not None else ''
        })
        return _obj


