# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.runtime_hitl_control import RuntimeHitlControl
from openapi_client.models.runtime_query_expansion_control import RuntimeQueryExpansionControl
from openapi_client.models.runtime_rerank_control import RuntimeRerankControl
from typing import Optional, Set
from typing_extensions import Self

class RuntimeAgentRunControls(BaseModel):
    """
    RuntimeAgentRunControls
    """ # noqa: E501
    hitl: Optional[RuntimeHitlControl] = None
    query_expansion: Optional[RuntimeQueryExpansionControl] = None
    rerank: Optional[RuntimeRerankControl] = None
    __properties: ClassVar[List[str]] = ["hitl", "query_expansion", "rerank"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuntimeAgentRunControls from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of hitl
        if self.hitl:
            _dict['hitl'] = self.hitl.to_dict()
        # override the default output from pydantic by calling `to_dict()` of query_expansion
        if self.query_expansion:
            _dict['query_expansion'] = self.query_expansion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rerank
        if self.rerank:
            _dict['rerank'] = self.rerank.to_dict()
        # set to None if hitl (nullable) is None
        # and model_fields_set contains the field
        if self.hitl is None and "hitl" in self.model_fields_set:
            _dict['hitl'] = None

        # set to None if query_expansion (nullable) is None
        # and model_fields_set contains the field
        if self.query_expansion is None and "query_expansion" in self.model_fields_set:
            _dict['query_expansion'] = None

        # set to None if rerank (nullable) is None
        # and model_fields_set contains the field
        if self.rerank is None and "rerank" in self.model_fields_set:
            _dict['rerank'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuntimeAgentRunControls from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hitl": RuntimeHitlControl.from_dict(obj["hitl"]) if obj.get("hitl") is not None else None,
            "query_expansion": RuntimeQueryExpansionControl.from_dict(obj["query_expansion"]) if obj.get("query_expansion") is not None else None,
            "rerank": RuntimeRerankControl.from_dict(obj["rerank"]) if obj.get("rerank") is not None else None
        })
        return _obj


