# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.citation_source_row import CitationSourceRow
from typing import Optional, Set
from typing_extensions import Self

class SubQuestionArtifacts(BaseModel):
    """
    SubQuestionArtifacts
    """ # noqa: E501
    citation_rows_by_index: Optional[Dict[str, CitationSourceRow]] = None
    expanded_queries: Optional[List[StrictStr]] = None
    reranked_docs: Optional[List[CitationSourceRow]] = None
    retrieval_provenance: Optional[List[Dict[str, Any]]] = None
    retrieved_docs: Optional[List[CitationSourceRow]] = None
    sub_answer: Optional[StrictStr] = ''
    sub_question: StrictStr
    __properties: ClassVar[List[str]] = ["citation_rows_by_index", "expanded_queries", "reranked_docs", "retrieval_provenance", "retrieved_docs", "sub_answer", "sub_question"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubQuestionArtifacts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in citation_rows_by_index (dict)
        _field_dict = {}
        if self.citation_rows_by_index:
            for _key_citation_rows_by_index in self.citation_rows_by_index:
                if self.citation_rows_by_index[_key_citation_rows_by_index]:
                    _field_dict[_key_citation_rows_by_index] = self.citation_rows_by_index[_key_citation_rows_by_index].to_dict()
            _dict['citation_rows_by_index'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in reranked_docs (list)
        _items = []
        if self.reranked_docs:
            for _item_reranked_docs in self.reranked_docs:
                if _item_reranked_docs:
                    _items.append(_item_reranked_docs.to_dict())
            _dict['reranked_docs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in retrieved_docs (list)
        _items = []
        if self.retrieved_docs:
            for _item_retrieved_docs in self.retrieved_docs:
                if _item_retrieved_docs:
                    _items.append(_item_retrieved_docs.to_dict())
            _dict['retrieved_docs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubQuestionArtifacts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "citation_rows_by_index": dict(
                (_k, CitationSourceRow.from_dict(_v))
                for _k, _v in obj["citation_rows_by_index"].items()
            )
            if obj.get("citation_rows_by_index") is not None
            else None,
            "expanded_queries": obj.get("expanded_queries"),
            "reranked_docs": [CitationSourceRow.from_dict(_item) for _item in obj["reranked_docs"]] if obj.get("reranked_docs") is not None else None,
            "retrieval_provenance": obj.get("retrieval_provenance"),
            "retrieved_docs": [CitationSourceRow.from_dict(_item) for _item in obj["retrieved_docs"]] if obj.get("retrieved_docs") is not None else None,
            "sub_answer": obj.get("sub_answer") if obj.get("sub_answer") is not None else '',
            "sub_question": obj.get("sub_question")
        })
        return _obj


