# coding: utf-8

"""
    agent-search

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SubQuestionAnswer(BaseModel):
    """
    SubQuestionAnswer
    """ # noqa: E501
    answerable: Optional[StrictBool] = False
    expanded_query: Optional[StrictStr] = ''
    sub_agent_response: Optional[StrictStr] = ''
    sub_answer: StrictStr
    sub_question: StrictStr
    tool_call_input: Optional[StrictStr] = ''
    verification_reason: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["answerable", "expanded_query", "sub_agent_response", "sub_answer", "sub_question", "tool_call_input", "verification_reason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubQuestionAnswer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubQuestionAnswer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "answerable": obj.get("answerable") if obj.get("answerable") is not None else False,
            "expanded_query": obj.get("expanded_query") if obj.get("expanded_query") is not None else '',
            "sub_agent_response": obj.get("sub_agent_response") if obj.get("sub_agent_response") is not None else '',
            "sub_answer": obj.get("sub_answer"),
            "sub_question": obj.get("sub_question"),
            "tool_call_input": obj.get("tool_call_input") if obj.get("tool_call_input") is not None else '',
            "verification_reason": obj.get("verification_reason") if obj.get("verification_reason") is not None else ''
        })
        return _obj


